### ISSUE TITLE
Date-time updates

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#122]
1. The French UI has english default text for the date-time fields (in all types - single date, date range, multiple dates). 
Th screenshot shows the error.
Please update the time fields as follows in both the French and English UIs (Heure de début / Start time ;  Heure de fin / End time):
Display the time format (like we do for dates). Display hh:mm as the default text in both English and French UIs.

![Image](https://user-images.githubusercontent.com/64489312/217073576-0a1ca55f-696d-4a75-bbd2-9236528a7288.png)

2. In the French UI, please replace the time selector dropdown (for setting the time of the event) with a 24 hour format. This will make it easier for our clients to copy paste times from other events in Quebec. In the English UI, it will remain a 12 hour format (as is today).

3. For setting dates please **change the date format from month-day-year to day-month-year**; this is the preferred format used by our customers in Quebec and many other places (except for the USA). 
In the English UI, change it from MM/DD/YYYY to DD/MM/YYYY 
In the french UI, it would be changed to JJ/MM/AAAA 
When you change the format, also change the default text to match.

@saumier this is ready for you.

**Comment by AbhishekPAnil** [comment]
ESTIMATES 1hr

Subtasks : 
1.Change the translation texts for french.
2.Change date formats for en and fr.

**Comment by saumier** [comment]
@AbhishekPAnil This issue is related to i18n to change the date format from month-day-year to day-month-year. You may need to increase this estimate.

**Comment by troughc** [comment]
@AbhishekPAnil I just noticed that the date picker is in English in the French UI - do you have access to a french version of the date picker or would you have to create one? If so, what would you need from me and how long do you think it would take?
 (see screenshot for english date picker in french ui):


![Image](https://user-images.githubusercontent.com/64489312/223140486-930f3a22-9ddc-475a-b501-e6aa40e8218d.png)

**Comment by troughc** [comment]
All the date-time updates are working perfectly by the way!  
And no @AbhishekPAnil, I did not ask you to update the picker (I missed it). thanks for checking I will wait to hear back from you

**Comment by AbhishekPAnil** [comment]
@troughc  I am able to configure it like this .

![Image](https://user-images.githubusercontent.com/117100211/223152739-685a5b26-0668-401f-ab67-13c1332f9cc8.png)

**Comment by troughc** [comment]
@AbhishekPAnil and we can now use this anywhere we need a date picker in French. Thank you!

**Comment by AbhishekPAnil** [comment]
just out of curiousity - is it me or are the days of the week offset a little to the left from the dates in the calendar (in the columns)?--------------->
@troughc Yes it is,thank you for pointing it out. .I have corrected the alignment and updated the french version of calendar in staging .Please do check it out and let me know if any changes are needed.

**Comment by troughc** [comment]
Hi @AbhishekPAnil I still see the English date picker in the French UI (in chrome). Using the develeloper tools, I did an 'empty cache and hard reload' but it doesn't change anything.

![Image](https://user-images.githubusercontent.com/64489312/223489703-01e66cc7-401a-4310-8562-0a99740a417e.png)



![Image](https://user-images.githubusercontent.com/64489312/223489780-0d8d8d89-eada-4b60-82a2-418810b7002e.png)

**Comment by troughc** [comment]
Tested Staging on Chrome: PASSED
