### ISSUE TITLE
quick create dropdown doesn't have french translation

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1687]
Please translate the headers in the dropdown for quick create and import screens

My Footlight - Mon Footlight
Imports from Footlight -  Importées de Footlight
Imports from Artsdata - Importées d'Artsdata

**Comment by troughc** [comment]
@AbhishekPAnil was this ever translated in the past?

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil was this ever translated in the past?

Yes this was.But it was missing in some pages.

**Comment by troughc** [comment]
Okay great. Please use the translation that was supplied the last time (so it is consistent) :)

**Comment by troughc** [comment]
@SyamBabu-M I don't seem to be able to access the PR: https://pr-1728.dla06mbe0wyl7.amplifyapp.com/

**Comment by AbhishekPAnil** [comment]
@troughc Could you please check again.
This happened because there was an environment variable change while merging 1338.The PR link should be working fine right now.

**Comment by troughc** [comment]
Hi @AbhishekPAnil.....Still not working for me.

<img width="502" alt="Image" src="https://github.com/user-attachments/assets/e8a8ab95-b75c-402e-a595-118981e5d725" />

**Comment by AbhishekPAnil** [comment]
@troughc Could you please check again.I was able to login using my account.Also i did my round of testing with the translations.

**Comment by troughc** [comment]
Tested in different entities, translations seem good! PASSED
